[package]
name = "Practical2"
version = "1.0.0"
authors = []

[addresses]
hem_acc = "0x353c22368abd20066d5a1d94de5c52eb05388b1b492194c5f8e3d9cf3e6dc40c"  

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "devnet" }

