[package]
name = "Practical2"
version = "1.0.0"
authors = []

[addresses]
hem_acc = "0x13d4d34675eb770aff8668e600d2f79e902659153cc298d6192bdc74e05f351c"  

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "devnet" }

