[package]
name = "Practical2"
version = "1.0.0"
authors = []

[addresses]
hem_acc = "0x9ed87d4454640d7bdc2fb874f4a2926c0f87fd346bef772e0d013690502ab643"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "devnet" }

